version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  
    restart: "unless-stopped"
    volumes:
      -  ./src:/usr/src/app/src
    image: ez-ask-app-dev
